
colors:
  primary: "#38bdf8" # Vibrant blue
  secondary: "#818cf8" # Soft purple
  background: "#0f172a" # Dark navy
  text: "#f1f5f9" # Light gray
  accent: "#f472b6" # Pink accent


fonts:
  body: "Inter, Segoe UI, Helvetica, Arial, sans-serif"
  heading: "Inter-Bold, Segoe UI Bold, Helvetica-Bold, Arial Black, sans-serif"
  code: "Fira Mono, Menlo, Monaco, Courier, monospace"

layout:
  margin: 60
  slide_width: 612
  slide_height: 792
  orientation: "portrait"  # "portrait" or "landscape"

css: |
  .slide {
    page-break-after: always;
    background: #0f172a;
    padding: 48px 56px;
    font-family: Inter, Segoe UI, Helvetica, Arial, sans-serif;
    color: #f1f5f9;
    box-shadow: 0 4px 32px 0 #000a1a33;
    border-radius: 18px;
    border: 1px solid #1e293b;
    position: relative;
    min-height: 600px;
  }

  .slide header {
    border-bottom: 2px solid #38bdf8;
    padding-bottom: 18px;
    margin-bottom: 36px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .slide header h1 {
    margin: 0;
    font-size: 28px;
    color: #38bdf8;
    letter-spacing: 0.5px;
    font-family: Inter-Bold, Segoe UI Bold, Helvetica-Bold, Arial Black, sans-serif;
    text-shadow: 0 2px 8px #0ea5e933;
  }

  .slide-number {
    color: #818cf8;
    font-size: 14px;
    font-weight: 600;
    background: #1e293b;
    border-radius: 8px;
    padding: 2px 10px;
    margin-left: 12px;
    box-shadow: 0 1px 4px #0003;
  }

  .slide main {
    min-height: 420px;
    font-size: 20px;
    line-height: 1.7;
    color: #f1f5f9;
  }

  .slide footer {
    margin-top: 36px;
    padding-top: 14px;
    border-top: 1px solid #334155;
    font-size: 14px;
    color: #818cf8;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .author {
    color: #f472b6;
    font-weight: 600;
    font-size: 15px;
  }

  .date {
    color: #818cf8;
    font-size: 14px;
  }

  h1, h2, h3, h4, h5, h6 {
    color: #38bdf8;
    margin-top: 0;
    font-family: Inter-Bold, Segoe UI Bold, Helvetica-Bold, Arial Black, sans-serif;
    letter-spacing: 0.5px;
    text-shadow: 0 2px 8px #0ea5e933;
  }

  h2 {
    font-size: 24px;
    color: #f472b6;
    margin-bottom: 12px;
  }

  h3 {
    font-size: 20px;
    color: #818cf8;
    margin-bottom: 10px;
  }

  code {
    background-color: #1e293b;
    color: #38bdf8;
    padding: 3px 7px;
    border-radius: 5px;
    font-family: Fira Mono, Menlo, Monaco, Courier, monospace;
    font-size: 16px;
    box-shadow: 0 1px 4px #0002;
  }

  pre {
    background-color: #18181b;
    color: #f1f5f9;
    padding: 20px 24px;
    border-radius: 10px;
    border-left: 5px solid #38bdf8;
    font-family: Fira Mono, Menlo, Monaco, Courier, monospace;
    font-size: 16px;
    box-shadow: 0 2px 12px #0004;
    margin-bottom: 24px;
    overflow-x: auto;
  }

  pre code {
    background: none;
    color: inherit;
    padding: 0;
    border-radius: 0;
    font-size: inherit;
    box-shadow: none;
  }

  ul, ol {
    margin-left: 24px;
    margin-bottom: 18px;
  }

  ul li[data-task="true"] {
    list-style: none;
    position: relative;
    padding-left: 28px;
    margin-bottom: 8px;
  }

  ul li[data-task="true"]:before {
    content: "✓ ";
    color: #10b981;
    font-weight: bold;
    position: absolute;
    left: 0;
    top: 0;
  }

  ul li[data-task="false"]:before {
    content: "☐ ";
    color: #6b7280;
    position: absolute;
    left: 0;
    top: 0;
  }

  blockquote {
    border-left: 4px solid #f472b6;
    background: #1e293b;
    color: #f472b6;
    padding: 12px 24px;
    border-radius: 8px;
    margin: 18px 0;
    font-style: italic;
    box-shadow: 0 1px 6px #0002;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 24px;
    background: #18181b;
    color: #f1f5f9;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 1px 8px #0003;
  }

  th, td {
    padding: 12px 16px;
    border-bottom: 1px solid #334155;
  }

  th {
    background: #1e293b;
    color: #38bdf8;
    font-weight: 700;
  }

  tr:last-child td {
    border-bottom: none;
  }
